addSbtPlugin("com.typesafe.sbt"  % "sbt-multi-jvm"       % "0.4.0")
addSbtPlugin("com.dwijnand"      % "sbt-dynver"          % "3.0.0")
addSbtPlugin("se.marcuslonnberg" % "sbt-docker"          % "1.5.0")
addSbtPlugin("org.scalameta"     % "sbt-scalafmt"        % "2.0.0")
addSbtPlugin("com.typesafe.sbt"  % "sbt-native-packager" % "1.3.25")
